# Copyright 2024 TikTok Pte. Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

singleuser:
    image:
        name: us-docker.pkg.dev/${project_id}/${artifact_repo_docker}/datascience-notebook-with-dcr
        tag: ${tag}
        pullPolicy: Always
    cmd: null
    nodeSelector: { iam.gke.io/gke-metadata-server-enabled: "true"}
    serviceAccountName: $single_user_pod_sa
    extraEnv:
        NOTEBOOK_ARGS: '--NotebookApp.terminals_enabled=False --NotebookApp.allow_root=False'
        JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
        DATA_CLEAN_ROOM_HOST: "$api"
        DEPLOYMENT_ENV: "$env"
        PROJECT_ID: "$project_id"
        KEY_LOCALTION: "$region"
    networkPolicy:
        egressAllowRules:
            cloudMetadataServer: true
    cloudMetadata:
        blockWithIptables: false