CloudProvider:
  GCP:
    Project: "$PROJECTID"
    ProjectNumber: $PROJECTNUMBER
    Repository: "dcr-ENV-user-images"
    HubBucket: "dcr-ENV-hub"
    InputBucket: "dcr-ENV-input"
    CvmServiceAccount: "dcr-ENV-cvm-sa"
    Zone: "$ZONE"
    Region: "$REGION"
    CPUs: 2
    DiskSize: 50
    DebugInstanceImageSource: "projects/confidential-space-images/global/images/confidential-space-debug-240200"
    ReleaseInstanceImageSource: "projects/confidential-space-images/global/images/confidential-space-240200"
    Debug: false
    KeyRing: "dcr-ENV-keyring"
    WorkloadIdentityPool: "dcr-ENV-pool"
    IssuerUri: "https://confidentialcomputing.googleapis.com/"
    AllowedAudiences: ["https://sts.googleapis.com"]
    Network: "dcr-ENV-network"
    Subnetwork: "dcr-ENV-subnetwork"
    Env: ENV
Cluster:
  PodServiceAccount: "dcr-k8s-pod-sa"